### Create Room
POST http://localhost:3000/api/rooms
Content-Type: application/json
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzY5NTMzMDQ4LCJleHAiOjE3Njk1NzYyNDh9.Y5d1v2yA3K-GyIM2d3FdfIQiWA8T3C7Bmfbs2tfmX_M"

{
  "name": "Room A"
}

###

### Create Another Room
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
  "name": "Conference Hall"
}

###

### List All Rooms
GET http://localhost:3000/api/rooms

###

### Update Room (Replace ID with actual UUID)
PUT http://localhost:3000/api/rooms/b3c4c561-2fdd-4539-b012-023bff0eec54
Content-Type: application/json

{
  "name": "Updated Room Name"
}

###

### Delete Room (Replace ID with actual UUID)
DELETE http://localhost:3000/api/rooms/ddb8af7b-ab04-46b1-83a3-c2ca209ed6bc

###
