## Request to delete a user by ID
DELETE  http://localhost:3000/api/users/0179c836-63e2-4370-8732-f5e17875838a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzY5NTMyMjk5LCJleHAiOjE3Njk1NzU0OTl9.NuZdUrzAZy-N5NGq-7N1NAy46u67KnuYcVc4W7x_FI8

